name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # user: michaelneuper
          # template: classic
          # base: header, activity, community, repositories, metadata
          # config_timezone: Africa/Johannesburg
          # plugin_habits: yes
          # plugin_habits_charts_type: classic
          # plugin_habits_days: 14
          # plugin_habits_facts: yes
          # plugin_habits_from: 200
          # plugin_habits_languages_limit: 8
          # plugin_habits_languages_threshold: 0%
          # plugin_leetcode: yes
          # plugin_leetcode_limit_recent: 2
          # plugin_leetcode_limit_skills: 10
          # plugin_leetcode_sections: solved
          # plugin_leetcode_user: michaelneuper
          # plugin_repositories: yes
          # plugin_repositories_featured: hugo-texify3, dotfiles
          # plugin_repositories_order: featured, pinned, starred, random
          # plugin_rss: yes
          # plugin_rss_limit: 2
          # plugin_rss_source: https://michaelneuper.com/index.xml
